name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  mobile_scanner: ^6.0.2
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Knewave
      fonts:
        - asset: assets/fonts/Knewave-Regular.ttf

