name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.8.3
  hive: ^4.0.0-dev.2 
  isar_flutter_libs: ^4.0.0-dev.13
  pinput: ^5.0.1
  flutter_layout_grid: ^2.0.7
  sizer: ^3.0.5
  drop_down_list: ^2.0.0
  flex_color_picker: ^3.7.0
  flutter_expandable_fab: ^2.3.0
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Knewave
      fonts:
        - asset: assets/fonts/Knewave-Regular.ttf

